# yamllint configuration for echo-server
# See https://yamllint.readthedocs.io for documentation

extends: default

rules:
  # Allow longer lines (default is 80)
  line-length:
    max: 120
    level: warning

  # Don't require document start marker (---)
  document-start: disable

  # Allow inline mappings
  braces:
    max-spaces-inside: 1
    level: error

  # Allow inline sequences
  brackets:
    max-spaces-inside: 1
    level: error

  # Indentation rules
  indentation:
    spaces: 2
    indent-sequences: true

  # Allow duplicate keys in some cases (for anchors/aliases)
  key-duplicates: enable

  # Comments
  comments:
    min-spaces-from-content: 1
    require-starting-space: true

  # Truthy values
  truthy:
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
    check-keys: false
