name: Clean GHCR

on:
  workflow_run:
    workflows:
      - "Push Docker Image"
      - "Release"
    types:
      - completed
  workflow_dispatch:

jobs:
  clean-up-ghcr:
    name: Clean up docker images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: 'Clean up docker images'
        uses: dataaxiom/ghcr-cleanup-action@d52806a0dc70b430571a37da1fde39733ffd640f # v1
        with:
          delete-untagged: true
          validate: true
          token: ${{ secrets.GITHUB_TOKEN }}
