name: "PR Size Labeler"

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          xs_label: 'size/XS'
          xs_max_size: '10'
          s_label: 'size/S'
          s_max_size: '100'
          m_label: 'size/M'
          m_max_size: '500'
          l_label: 'size/L'
          l_max_size: '1000'
          xl_label: 'size/XL'
          fail_if_xl: 'false'
          message_if_xl: >
            This PR exceeds the recommended size of 500 lines.
            Please consider breaking it into smaller PRs for easier review.
          ignore_line_deletions: 'true'
          ignore_file_deletions: 'true'
          files_to_ignore: |
            "go.sum"
